// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNyhhFbV6_rj24h09RV8Cl0IZoMUg_M7w',
    appId: '1:969288485113:web:279cbfa8a7bd38cf103a28',
    messagingSenderId: '969288485113',
    projectId: 'fir-flutter-app-e6a2f',
    authDomain: 'fir-flutter-app-e6a2f.firebaseapp.com',
    storageBucket: 'fir-flutter-app-e6a2f.appspot.com',
    measurementId: 'G-WDJR5LDEFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVrfz_hW9TRCi48ExSNmjJ8dgQ0jcn65o',
    appId: '1:969288485113:android:1773b5c8e3545844103a28',
    messagingSenderId: '969288485113',
    projectId: 'fir-flutter-app-e6a2f',
    storageBucket: 'fir-flutter-app-e6a2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjiQR1gInI7gbbv06QAk3NSRAF6YygB9Q',
    appId: '1:969288485113:ios:0213d15c564b2379103a28',
    messagingSenderId: '969288485113',
    projectId: 'fir-flutter-app-e6a2f',
    storageBucket: 'fir-flutter-app-e6a2f.appspot.com',
    androidClientId: '969288485113-ebppssu3cpmhg49roiafbf8657kgj5et.apps.googleusercontent.com',
    iosClientId: '969288485113-utdrkmbokedum5on79iql90jub6vppln.apps.googleusercontent.com',
    iosBundleId: 'com.dialiax.demoApp',
  );

}